behaviors:
  FighterAIAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 600
      buffer_size: 60000
      learning_rate: 0.00001
      beta: 0.0005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 6
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 330
      num_layers: 2
      vis_encode_type: simple
      #memory:
       # sequence_length: 32
        #memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 1.0e-4
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 10000
    checkpoint_interval: 50000
    threaded: true
    self_play:
      save_steps: 50000
      team_change: 200000
      swap_steps: 2000
      window: 10
      play_against_latest_model_ratio: 0.5
      initial_elo: 1200.0